CREATE WAREHOUSE DE_AA_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE;

CREATE DATABASE DE_AA_DB;

CREATE SCHEMA DE_AA_DB.DE_AA_SCHEMA;

CREATE OR REPLACE STAGE DE_AA_DB.DE_AA_SCHEMA.DE_AA_STAGE
FILE_FORMAT = 'DE_AA_FF';

CREATE FILE FORMAT DE_AA_FF
field_delimiter = ','
type = 'csv'
field_optionally_enclosed_by = '"';

DESCRIBE STAGE DE_AA_STAGE;

PUT file://C:\Users\lucas\dbt_airflow\dbt\cosmoproject\customers.csv
@DE_AA_DB.DE_AA_SCHEMA.DE_AA_STAGE;

COPY INTO DE_AA_DB.DE_AA_SCHEMA.bookings_1 FROM @DE_AA_DB.DE_AA_SCHEMA.DE_AA_STAGE/bookings_1.csv;

CREATE OR REPLACE TABLE DE_AA_DB.DE_AA_SCHEMA.bookings_1 (
id VARCHAR(255)
,booking_reference VARCHAR(255)
,hotel VARCHAR(255)
,booking_date VARCHAR(255)
,cost VARCHAR(255)
);

REMOVE @DE_AA_DB.DE_AA_SCHEMA.DE_AA_STAGE;